<<<<<<< HEAD
allowBuilds:
  esbuild: true
  unrs-resolver: true
onlyBuiltDependencies:
=======
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
>>>>>>> 155aef882148eb5d140b5d419f123039d4238e5d
  - esbuild
  - unrs-resolver
