<<<<<<< HEAD
allowBuilds:
  esbuild: true
  unrs-resolver: true
onlyBuiltDependencies:
=======
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
>>>>>>> c78877ecbba1ceb5d7507f33bcd5d55b9fb9431b
  - esbuild
  - unrs-resolver
